package com.newterraearth.tfe.world;

public final class NTELayerIds {

  public static int COLLISIONAL_MOUNTAINS;
  public static int OCEANIC_VOLCANIC_ARC;
  public static int OCEAN_ATOLLS;
  public static int DEEP_OCEAN_ATOLLS;
  public static int OCEAN_RIDGE;
  public static int RIFT_VALLEY;
  public static int RIFT_LAKE;
  public static int VOLCANIC_MOUNTAIN_ISLANDS;
  public static int VOLCANIC_ISLAND;
  public static int PLATEAU_WIDE;
  public static int STAIR_STEP_CANYONS;
  public static int MESAS;
  public static int BUTTES;
  public static int ROCKY_PLATEAU;
  public static int TOWER_KARST_PLAINS;
  public static int TOWER_KARST_CANYONS;
  public static int TOWER_KARST_HILLS;
  public static int TOWER_KARST_HIGHLANDS;
  public static int TOWER_KARST_LAKE;
  public static int TOWER_KARST_BAY;
  public static int EXTREME_DOLINE_PLATEAU;
  public static int EXTREME_DOLINE_MOUNTAINS;
  public static int BURREN_PLATEAU;
  public static int BURREN_BADLANDS;
  public static int BURREN_BADLANDS_TALL;
  public static int BURREN_ROCHE_MOUTONEE;
  public static int BURREN_PLAINS;
  public static int ACTIVE_SHIELD_VOLCANO;
  public static int DORMANT_SHIELD_VOLCANO;
  public static int EXTINCT_SHIELD_VOLCANO;
  public static int ANCIENT_SHIELD_VOLCANO;
  public static int SUNKEN_SHIELD_VOLCANO;
  public static int SHIELD_VOLCANO_SHORE;
  public static int OLD_SHIELD_VOLCANO_SHORE;
  public static int ICE_SHEET;
  public static int ICE_SHEET_MOUNTAINS;
  public static int ICE_SHEET_OCEANIC_MOUNTAINS;
  public static int ICE_SHEET_VOLCANIC_MOUNTAINS;
  public static int ICE_SHEET_VOLCANIC_OCEANIC_MOUNTAINS;
  public static int ICE_SHEET_SHIELD_VOLCANO;
  public static int ICE_SHEET_TUYAS;
  public static int SUBGLACIAL_LAKE;
  public static int ICE_SHEET_EDGE;
  public static int ICE_SHEET_TUYAS_EDGE;
  public static int ICE_SHEET_SHORE;
  public static int GLACIATED_MOUNTAINS;
  public static int GLACIATED_OCEANIC_MOUNTAINS;
  public static int GLACIATED_VOLCANIC_MOUNTAINS;
  public static int GLACIATED_VOLCANIC_OCEANIC_MOUNTAINS;
  public static int MELTWATER_LAKE;
  public static int GLACIATED_SHIELD_VOLCANO;
  public static int GLACIALLY_CARVED_MOUNTAINS;
  public static int GLACIALLY_CARVED_OCEANIC_MOUNTAINS;
  public static int GLACIALLY_CARVED_VOLCANIC_MOUNTAINS;
  public static int GLACIALLY_CARVED_VOLCANIC_OCEANIC_MOUNTAINS;
  public static int DRUMLINS;
  public static int TUYAS;
  public static int KNOB_AND_KETTLE;
  public static int PATTERNED_GROUND;
  public static int INVERTED_PATTERNED_GROUND;
  public static int HIGHLANDS;
  public static int OLD_MOUNTAINS;
  public static int ROLLING_HILLS;

  private NTELayerIds() {}
}
