# Loader metadata
modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"

# TFC: Real World
[[mods]]
    modId = "${modId}"
    version = "${modVersion}"
    displayName = "TFC: Real World"
    credits = "Earth-like world generation using real-world maps, filled with original TerraFirmaCraft content"
    authors = "yazloysasha"
    description = '''TFC: Real World generates a believable Earth-like world using real-world maps for continents, mountains, hotspots and climate, fully populated with TerraFirmaCraft's original content and progression.'''

# Dependencies
[[dependencies.${modId}]]
    modId = "tfc"
    mandatory = true
    versionRange = "${tfcVersionRange}"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${modId}]]
    modId = "forge"
    mandatory = true
    versionRange = "[40.1.73,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${modId}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraftVersionRange}"
    ordering = "AFTER"
    side = "BOTH"
